package com.example.jrtrail.model.downstream;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.ArrayList;
import java.util.List;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Liveness")
public class LivenessStatusMap {
    @DynamoDBHashKey(attributeName = "idd")
    @DynamoDBAutoGeneratedKey
    private String idd;
    @DynamoDBAttribute(attributeName = "status")
    private List<LivenessStatusNew> modules = new ArrayList<>();
}
