package com.example.jrtrail.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.ArrayList;
import java.util.List;

@Getter
@Setter
@NoArgsConstructor
@DynamoDBTable(tableName = "Application")
public class Application {
    @DynamoDBHashKey(attributeName = "ApplicationID")
    @DynamoDBAutoGeneratedKey
    private String applicationID;
    @DynamoDBAttribute(attributeName = "title")
    private String title;

    @DynamoDBAttribute(attributeName = "modules")
//    private Modules modules;
    private List<Modules> modules = new ArrayList<>();

    public Application(String applicationID, String title, /*Modules modules*/ List<Modules> modules) {
        this.applicationID = applicationID;
        this.title = title;
        if (modules != null) this.modules = modules;
//        this.modules = modules;

    }
}
